
version: '2.2'

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./_nginx/ssl:/etc/letsencrypt
      - ./_nginx/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done;'"
  riccardopapucci:
      image: papucci/nginx-riccardopapucci:0.0.14
      ports:
        - 80:8080
      volumes:
        - ./_nginx/ssl:/etc/letsencrypt
        - ./_nginx/www:/var/www/certbot    
