version: '2.2'

services:
  riccardopapucci:
      image: papucci/nginx-riccardopapucci:0.1.1
      ports:
          - 80:8080
          - 443:443
      volumes:
        - ./_nginx/ssl:/etc/letsencrypt
        - ./_nginx/www:/var/www/certbot  
    
 