version: '2.2'

services:
  riccardopapucci:
      image: papucci/nginx-riccardopapucci:0.0.14
      ports:
          - 80:8080
          - 443:443
      volumes:
        - ./_nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./_nginx/ssl:/etc/nginx/ssl
        - ./_nginx/www:/var/www/certbot
        - ./_site:/usr/share/nginx/html
    
 